version: '3.4'
services:
  prometheus:
    user: 0:0
    image: prom/prometheus
    container_name: prometheus
    volumes:
     - ./etc/prometheus/:/etc/prometheus/
     - ./data/prometheus/:/prometheus/
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus 
    - --storage.tsdb.retention=200h
    ports:
     - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
     - 3000:3000
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
